### ISSUE TITLE
Application Freeze

### ISSUE THREAD

**Issue by Cheyans** [mohamed-arradi/AirpodsBattery-Monitor-For-Mac#14]
After about an hour of usage the application froze and I couldn't click on the menu bar and percentage didn't update. 
Are there logs stored anywhere for me to upload to help debug?

**Comment by Cheyans** [comment]
It looks like if the airpods are connected to the mac and then I try and connect to them with my iPhone forcing the connection swap the application freezes.

**Comment by mohamed-arradi** [comment]
@Cheyans Indeed I noticed that. I have not been able to determine why this is happening yet. Your clue may be a good one. 

There is no log attached to that. I don't do logging for bluetooth .

**Comment by mohamed-arradi** [comment]
@Cheyans  I figured it out that some memory leaks was happening. 

I fixed all of them. It should help a lot the stability and reducing the memory footprint of the widget. 

Can you do some tests on your end also to see if that PR is doing the fix required for this.

**Comment by Cheyans** [comment]
It worked for a full day without freezing, thanks!
