### ISSUE TITLE
Customizable font

### ISSUE THREAD

**Issue by Cheyans** [mohamed-arradi/AirpodsBattery-Monitor-For-Mac#15]
It would be nice to be able to customize the font or allow for system font usage
It looks like the font is hardcoded to `Herculanum` https://github.com/mohamed-arradi/AirpodsBattery-Monitor-For-Mac/blob/63b6a4756fe8b48bfa0788eed787c2b357de43c5/AirpodsPro%20Battery/AirpodsPro%20Battery/Views/MainMenu.xib#L170

**Comment by mohamed-arradi** [comment]
@Cheyans I will be more up to having the font using the system one. Customizable font is not really a product feature. If someone require a specific font, he can always fork it and build it.

However I do agree, using the system one allow neutral aspect and follow the mac os system design. I will implement it
