### ISSUE TITLE
Extracting orientation sensor values?

### ISSUE THREAD

**Issue by bc** [mohamed-arradi/AirpodsBattery-Monitor-For-Mac#19]
https://thenextweb.com/plugged/2020/06/22/apple-brings-surround-sound-and-dolby-atmos-to-airpods-pro/

Just saw the WWDC talk that shows the airpod pros have orientation sensors. Having tapped into the battery status, any ideas on how to access the stream of orientation or accelerometer data?
thanks!

**Comment by mohamed-arradi** [comment]
Hi @bc ! sorry for the delay. Indeed the new airpods software will use spacial audio. As of now so far I did not found anything that can be grab on mac OS from the documentation. However i did not yet upgraded to Mac Big Sur beta for professionnal reason. 

When I will have a chance to get hands on it I will let you know. And indeed that could be a great feature to add in this open source app.

**Comment by bc** [comment]
Ah sounds good! There are going to be some very beautiful opportunities for head tracking while using a laptop with these data, maybe even doing head gaze detection for game design!

**Comment by mohamed-arradi** [comment]
@bc Hi Brian, 

it seems that Mac OS will not be able to enjoy the spacial audio features as it seems that it requires gyroscope hardware. 

https://www.reddit.com/r/AirpodsPro/comments/iucjwy/macbook_pro_spatial_audio/

I think this issue is at the moment, not possible to do on a Mac OS App.
