### ISSUE TITLE
Is it possible to add Airpods Pro icon？

### ISSUE THREAD

**Issue by DevLiuSir** [mohamed-arradi/AirpodsBattery-Monitor-For-Mac#22]
Is it possible to add Airpods Pro icon？

**Comment by mohamed-arradi** [comment]
Are you talking Airpods Pro icon on the status bar text ? If it is this I am not sure if the status bar text can contains icons (maybe html unicode icons )

**Comment by DevLiuSir** [comment]
Both the status bar and the display power icon can be considered to adapt to AirPods Pro.

**Comment by mohamed-arradi** [comment]
@DevLiuSir I will need to check if the status bar text can contain multiples images to it. At first search it seem not to be possible. Did you find something that allow this? this only solution that I am currently investigating is using icon unicode. but airpods does not seem to have some (only headset)

**Comment by mohamed-arradi** [comment]
@DevLiuSir After a few searches it seems that there is no way to display either an asset on the Mac OS Status Bar. 

More other there is not yet unicode character that can represent emoji type for Airpods. 

As of now I will consider this issue as impossible to be done. However if you find anything that can make one of those 2 assumptions above valid, then we can consider it.
