### ISSUE TITLE
can't detect new airpods with same name

### ISSUE THREAD

**Issue by karenwky** [mohamed-arradi/AirpodsBattery-Monitor-For-Mac#23]
I just got a new pair of airpods pro from apple store and named them with the same name as the old ones, but this app can't detect the new pair of airpods pro, and even when I clicked "Refresh Devices" it detects my non-airpods earphones in the "Connect to...". I've tried reinstall the app but still doesn't work.

**Comment by mohamed-arradi** [comment]
Hi,

That is a good finding. I will try to avoid just the name comparaison only and match MAC address + naming. Let me rework this. 

Thanks for the feedback

**Comment by mohamed-arradi** [comment]
@yyzz1010 can you check if you have any issue with the latest release build 2.0.0. Normally I was not able to reproduce your problem. I am comparing against name + device address, so it should be pretty unique.

**Comment by mohamed-arradi** [comment]
@yyzz1010  I assume that now the issue is fixed as no reply has been send. If the issue is still happening on the latest release as of now (2.1.0). please feel free to report a new issue.
