### ISSUE TITLE
Apple Watch Battery

### ISSUE THREAD

**Issue by cristiansori2** [mohamed-arradi/AirpodsBattery-Monitor-For-Mac#24]
I would like to code a service to show the Apple Watch battery too.Could it be implemented on this project?

**Comment by mohamed-arradi** [comment]
@cristiansori2 That is a very good idea. I thought to extends the functionnality. As of now, I am working on Widget for the new mac OS and M1 Macbook. 

Watch Battery can be a really good addition too. I need to do some research first.

**Comment by mohamed-arradi** [comment]
@cristiansori2 After researching information about it, it seems that only iPhone can get the Apple Watch battery. Therefore it won't be possible to have it on the Mac.
