### ISSUE TITLE
Can't hide app icon using hidden bar like apps

### ISSUE THREAD

**Issue by PkAIR** [mohamed-arradi/AirpodsBattery-Monitor-For-Mac#30]
Os: MAc OS Big Sur 11.6.1
App: Hidden bar from the app store (latest version - 1.8)

https://user-images.githubusercontent.com/30795278/141477865-49c84a4e-60e3-492b-9c30-93901a778be7.mov

**Comment by mohamed-arradi** [comment]
Thanks @PkAIR for the feedback ! Let me look into !

**Comment by mohamed-arradi** [comment]
Hi @PkAIR , can you try the latest Airpods Battery Monitor version ? I did run mine and your mac software and I do not have specific issue with hidding the software.

Only thing I have seen is that you need to put it after the **|** to be hidden 
https://user-images.githubusercontent.com/3295294/143765908-faa0d1a8-d04c-4d2d-9fe9-2768c75d2a48.mov

 Let me know in the next 2 weeks before I close the issue. Thanks

**Comment by PkAIR** [comment]
hey @mohamed-arradi, you're right. It works now like a charm. However I found another issue - you `buymeacofee` link gives 404 :( https://www.buymeacoffee.com/momolette

**Comment by mohamed-arradi** [comment]
@PkAIR thank you ! indeed i forgot about it ! I updated the link :)
