### ISSUE TITLE
Menu contains: "AVOutputDeviceBluetoothListeningModeNormal"

### ISSUE THREAD

**Issue by ElhemEnohpi** [mohamed-arradi/AirpodsBattery-Monitor-For-Mac#43]
<img width="443" alt="screenshot_96" src="https://user-images.githubusercontent.com/23618559/206804440-09e3ea55-886f-438e-8ab8-ab07bc7a3cd3.png">

Also, the menu says "No Airpods devices paired", but they are. It shows the correct battery level anyway.

Airpods Pro 2, macOS 13.0.1, listening mode is actually "noise cancellation".

**Comment by mohamed-arradi** [comment]
@ElhemEnohpi I saw that issue and I will fix it soon. thanks for raising it

**Comment by mohamed-arradi** [comment]
@ElhemEnohpi latest release [2.2.6](https://github.com/mohamed-arradi/AirpodsBattery-Monitor-For-Mac/releases/tag/2.2.6) hopefully should fix the issue that you are getting for the status bar text. Please re-open the issue if it does not.

**Comment by ElhemEnohpi** [comment]
@mohamed-arradi thanks for the improvement, the menu bar now shows "Normal Mode" instead of "AVOutputDevicebluetoothListeningModeNormal". However, it always shows "Normal Mode", regardless of what mode they are in, whether noise cancellation, transparency, or normal. So the message doesn't seem very useful.

Even if it showed the listening mode as I would expect, I don't really need to see that. I think it takes up too much space on the menu bar. Btw., I switched to using MenuBar Stats, because it has notifications for battery level, so I'm not using this anymore. But thanks anyway.
