### ISSUE TITLE
hide Name from task bar next to the icons

### ISSUE THREAD

**Issue by slug2020** [mohamed-arradi/AirpodsBattery-Monitor-For-Mac#46]
Hi, 
next to the battery indicator of the airpods is a very long name displayed on my taskbar with the following: AVOutputDeviceBluetoothListeningModeNormal

How can i disable that? Why is it there?

thanks for the awesome app!

**Comment by mohamed-arradi** [comment]
Hi @slug2020 , Yes indeed I am planning to remove that and put my own string there. It works in some macbook but not all.  I am glad you like it ! Thank you for the feedback. Will update here once an update is made.

**Comment by mohamed-arradi** [comment]
@slug2020 This issue has been now resolved. The listening mode is now removed from the new release. It was flaky and not really helpful after wards. 

A new smaller UI has been introduced now. 

Release is there: https://github.com/mohamed-arradi/AirpodsBattery-Monitor-For-Mac/releases/tag/2.2.7
