### ISSUE TITLE
Option for a compact menu bar display

### ISSUE THREAD

**Issue by MarksonChen** [mohamed-arradi/AirpodsBattery-Monitor-For-Mac#47]
Hi! I absolutely love seeing my AirPods' battery displayed right on the menu bar. Thank you for the app! 

However, the drawback preventing me from using the app is that the size of its menu bar item is taking 2/3 of the total available space for my 14-inch MacBook Pro:

<img width="1110" alt="image" src="https://github.com/mohamed-arradi/AirpodsBattery-Monitor-For-Mac/assets/46666959/bafe6cbf-5c29-4866-ac4e-9e832d37debb">

I would love it if there were an option to display only the two essential numbers in the most compact way possible. Perhaps something like this:
<img width="1110" alt="image" src="https://github.com/mohamed-arradi/AirpodsBattery-Monitor-For-Mac/assets/46666959/d3f02c51-44e2-46ee-90f0-e50f545fbe80">

Thank you!

**Comment by mohamed-arradi** [comment]
First of all thank you a lot for the feedback!  

This is a great idea and I am currently also reducing the space content as well. 

I am not sure about the vertical possibility but it will be either: L:R or as per your screenshot.

I will keep you posted!

**Comment by mohamed-arradi** [comment]
@MarksonChen Latest release[ 2.2.7](https://github.com/mohamed-arradi/AirpodsBattery-Monitor-For-Mac/releases/tag/2.2.7) contains now this improvements to reduce space on the status bar. 

Hope you will enjoy it. Re-open it if any other issue arise

**Comment by MarksonChen** [comment]
Thank you, I love it!
