### ISSUE TITLE
New Icon?

### ISSUE THREAD

**Issue by makeSmartio** [mohamed-arradi/AirpodsBattery-Monitor-For-Mac#48]
Just thinking that a new icon might freshen things up.. I just used GPT4, but there are some other free image generators out there. 
![DALL·E 2024-04-01 21 20 37 - AirPods with Battery Icon](https://github.com/mohamed-arradi/AirpodsBattery-Monitor-For-Mac/assets/38297650/9d15ee5d-0d8a-4f52-a7ad-5ddb5fbb094b)

Go ahead and close this "issue."

Thanks for your awesome project!

**Comment by mohamed-arradi** [comment]
Thank you so much for the feedback ! I needed one :)

**Comment by mohamed-arradi** [comment]
@makeSmartio the new icon has been used on the latest release [2.2.7](https://github.com/mohamed-arradi/AirpodsBattery-Monitor-For-Mac/releases/tag/2.2.7). Thanks to Chat GPT and your help to give a nice graphic bump.
